### ISSUE TITLE
ArduinoJson Assistant is OFFLINE

### ISSUE THREAD

**Issue by nodoubtman** [bblanchon/ArduinoJsonAssistant#1]
ArduinoJson Assistant is OFFLINE

can you fix it?

Thanks.
Marc.

**Comment by bblanchon** [comment]
Hi @nodoubtman,

I just tested it on Chrome, Firefox, Edge, and Safari, and it works fine.

* What browser version are you using?
* Is there anything in the developer console?

Best regards,
Benoit

**Comment by nodoubtman** [comment]
Firefox ca ne fonctionnait pas hier.
C'etair ecrit.
Lost?

Ca lair ok aujourdhui.
Merci 

Marc

**Comment by nodoubtman** [comment]
Salut Benoit: 

https://arduinojson.org/v6/assistant/#/step2

C'est écrit : Lost?

Aprèes la méthode SErialize ou deserialize...

Check ça.
A+
Marc.

**Comment by nodoubtman** [comment]
> 

Ça ne fonctionne pas encore pour firefox, mais google chrome ça fonctionne.
A+
Marc.

**Comment by bblanchon** [comment]
Hi Marc,

If you want to give me any chance to fix your issue, please answer:

* What Firefox version are you using?
* Is there anything in the developer console?

Best regards,
Benoit

**Comment by nodoubtman** [comment]
Hi Benoit,

FireFox 104.0 et ça m'affiche cela:

Lost? Watch the introduction on YouTube

The source code of the ArduinoJson Assistant is available on GitHub 

Merci.
A+!
Marc.

**Comment by bblanchon** [comment]
Hi Marc,

Thank you for the feedback.

I'm using Firefox 104 on Windows.
Are you using Windows too?

Is it possible that you're running a Firefox extension (maybe an adblocker) that could interfere with the Assistant?

While on the Assistant page, can you press on F12 and check if there are any errors logged in the "Console" tab?

![image](https://user-images.githubusercontent.com/5462433/187144225-dcfc10e9-f594-4d4c-95d3-92019a38ef1a.png)

Best regards,
Benoit

**Comment by nodoubtman** [comment]
Yes benoit i have Adbloker.
Runni g on Windows 10.
I will try.
Thanks.
Marc.

**Comment by nodoubtman** [comment]
Hey, i have upload the image i see in firefox.

Thanks.
Marc.
![ARDUINOJSON-ERROR](https://user-images.githubusercontent.com/15944995/187300709-2dc0870b-2604-4541-bb4c-3e5a4ca54279.png)

**Comment by bblanchon** [comment]
Thanks, Marc.
Unfortunately, the most important part is missing.
Do you think you can select all the text from the beginning and paste it here?

Also, can you disclose the names of the extensions installed on Firefox?
Can you try to disable some of them to see if the Assistant returns to life?

**Comment by nodoubtman** [comment]
Ce n'est pas grave, j'utilise Google Chrome.
Merci!
